spring:
  application:
    name: employee-service
  
  datasource:
    url: jdbc:postgresql://ic-pg-suveemo-backend.g.aivencloud.com:16255/defaultdb?sslmode=require
    username: avnadmin
    password: AVNS_RVCoXOLEqRwt4miw5gR
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9093

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,beans,mappings
  endpoint:
    health:
      show-details: always
