spring:
  application:
    name: employee-service
  
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
server:
  port: 9093

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,beans,mappings
  endpoint:
    health:
      show-details: always
