package com.ic.employee_service.enums;

public enum Designation {
    JUNIOR_DEVELOPER,
    SENIOR_DEVELOPER,
    LEAD_DEVELOPER,
    TECH_LEAD,
    ARCHITECT,
    MANAGER,
    SENIOR_MANAGER,
    DIRECTOR,
    VP,
    QA_ENGINEER,
    DEVOPS_ENGINEER,
    DATA_ANALYST,
    PRODUCT_MANAGER,
    BUSINESS_ANALYST,
    HR_SPECIALIST,
    ACCOUNTANT
}
